# Generated by Django 4.2 on 2023-09-23 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='uuid field'),
        ),
    ]
