# Generated by Django 4.2 on 2023-09-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_uuid_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid_field',
        ),
    ]
