# Generated by Django 4.2 on 2023-09-25 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(db_index=True, max_length=555, verbose_name='refresh token')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('expired_at', models.DateTimeField(db_index=True)),
                ('device', models.CharField(max_length=64, verbose_name='device')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Login',
                'verbose_name_plural': 'User Logins',
            },
        ),
    ]
