# Generated by Django 4.2 on 2023-09-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='refresh_token',
            field=models.CharField(db_index=True, max_length=1050, verbose_name='refresh token'),
        ),
    ]
