# Generated by Django 4.2 on 2023-09-25 23:19

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_authenticate', '0002_alter_userlogin_refresh_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userlogin',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
